/**
 * .env file generator — reads, writes, and backs up .env files.
 */

import { readFileSync, writeFileSync, renameSync, copyFileSync, existsSync, unlinkSync, chmodSync } from 'node:fs';

/** All supported env config keys. */
export interface EnvConfig {
  AGENT_RUNTIMES?: string;
  CONVOSKETCHPAD_DEFAULT_AGENT_RUNTIME?: string;
  CONVOSKETCHPAD_DEFAULT_AGENT_PROFILE?: string;
  OPENCLAW_GATEWAY_URL?: string;
  OPENCLAW_GATEWAY_TOKEN?: string;
  OPENCLAW_GATEWAY_TIMEZONE?: string;
  OPENCLAW_CONFIG_PATH?: string;
  OPENCLAW_BIN?: string;
  CODEX_BIN?: string;
  CODEX_WORKING_DIRECTORY?: string;
  PORT?: string;
  HOST?: string;
  ALLOWED_ORIGINS?: string;
  TRUSTED_PROXIES?: string;
  CONVOSKETCHPAD_DATA_DIR?: string;
  CONVOSKETCHPAD_ALLOW_INSECURE?: string;
  // Authentication
  CONVOSKETCHPAD_AUTH?: string;
  CONVOSKETCHPAD_SESSION_SECRET?: string;
  CONVOSKETCHPAD_SESSION_TTL?: string;
  CONVOSKETCHPAD_AUTH_MAX_FAILURES?: string;
  CONVOSKETCHPAD_AUTH_FAILURE_WINDOW?: string;
  CONVOSKETCHPAD_AUTH_LOCKOUT?: string;
}

/** Default values (matching server/lib/config.ts). */
export const DEFAULTS: Record<string, string> = {
  OPENCLAW_GATEWAY_URL: 'http://127.0.0.1:18789',
  PORT: '3080',
  HOST: '127.0.0.1',
};

/**
 * Generate a clean .env file.
 * Only writes values that differ from defaults (keeps .env minimal).
 * Writes each selected Runtime's required keys; OpenClaw always gets an
 * explicit token entry because it has no default.
 */
export function generateEnvContent(config: EnvConfig): string {
  const lines: string[] = [
    '# ConvoSketchpad Configuration',
    '# Generated by `npm run setup`',
    `# ${new Date().toISOString()}`,
    '',
  ];

  // Agent Runtime selection
  const runtimeIds = (config.AGENT_RUNTIMES ?? 'openclaw')
    .split(',')
    .map((runtimeId) => runtimeId.trim().toLowerCase())
    .filter(Boolean);
  lines.push(`AGENT_RUNTIMES=${runtimeIds.join(',')}`);
  if (config.CONVOSKETCHPAD_DEFAULT_AGENT_RUNTIME && config.CONVOSKETCHPAD_DEFAULT_AGENT_PROFILE) {
    lines.push(`CONVOSKETCHPAD_DEFAULT_AGENT_RUNTIME=${config.CONVOSKETCHPAD_DEFAULT_AGENT_RUNTIME}`);
    lines.push(`CONVOSKETCHPAD_DEFAULT_AGENT_PROFILE=${config.CONVOSKETCHPAD_DEFAULT_AGENT_PROFILE}`);
  }
  lines.push('');
  if (runtimeIds.includes('openclaw')) {
    lines.push('# OpenClaw Gateway');
    if (config.OPENCLAW_GATEWAY_URL && config.OPENCLAW_GATEWAY_URL !== DEFAULTS.OPENCLAW_GATEWAY_URL) {
      lines.push(`OPENCLAW_GATEWAY_URL=${config.OPENCLAW_GATEWAY_URL}`);
    }
    lines.push(`OPENCLAW_GATEWAY_TOKEN=${config.OPENCLAW_GATEWAY_TOKEN || ''}`);
    if (config.OPENCLAW_GATEWAY_TIMEZONE) {
      lines.push(`OPENCLAW_GATEWAY_TIMEZONE=${config.OPENCLAW_GATEWAY_TIMEZONE}`);
    }
    if (config.OPENCLAW_CONFIG_PATH) lines.push(`OPENCLAW_CONFIG_PATH=${config.OPENCLAW_CONFIG_PATH}`);
    if (config.OPENCLAW_BIN) lines.push(`OPENCLAW_BIN=${config.OPENCLAW_BIN}`);
    lines.push('');
  }
  if (runtimeIds.includes('codex')) {
    lines.push('# Codex App Server');
    if (config.CODEX_BIN) lines.push(`CODEX_BIN=${JSON.stringify(config.CODEX_BIN)}`);
    lines.push(`CODEX_WORKING_DIRECTORY=${JSON.stringify(config.CODEX_WORKING_DIRECTORY || '')}`);
    lines.push('');
  }

  // Server — always write PORT for clarity (even if default)
  const serverLines: string[] = [];
  serverLines.push(`PORT=${config.PORT || DEFAULTS.PORT}`);
  if (config.HOST && config.HOST !== DEFAULTS.HOST) {
    serverLines.push(`HOST=${config.HOST}`);
  }
  lines.push('# Server');
  lines.push(...serverLines);
  lines.push('');

  // Authentication
  if (
    config.CONVOSKETCHPAD_AUTH === 'true'
    || config.CONVOSKETCHPAD_SESSION_SECRET
    || config.CONVOSKETCHPAD_SESSION_TTL
    || config.CONVOSKETCHPAD_AUTH_MAX_FAILURES
    || config.CONVOSKETCHPAD_AUTH_FAILURE_WINDOW
    || config.CONVOSKETCHPAD_AUTH_LOCKOUT
  ) {
    const authLines: string[] = [];
    authLines.push(`CONVOSKETCHPAD_AUTH=${config.CONVOSKETCHPAD_AUTH || 'false'}`);
    if (config.CONVOSKETCHPAD_SESSION_SECRET) authLines.push(`CONVOSKETCHPAD_SESSION_SECRET=${config.CONVOSKETCHPAD_SESSION_SECRET}`);
    if (config.CONVOSKETCHPAD_SESSION_TTL) authLines.push(`CONVOSKETCHPAD_SESSION_TTL=${config.CONVOSKETCHPAD_SESSION_TTL}`);
    if (config.CONVOSKETCHPAD_AUTH_MAX_FAILURES) authLines.push(`CONVOSKETCHPAD_AUTH_MAX_FAILURES=${config.CONVOSKETCHPAD_AUTH_MAX_FAILURES}`);
    if (config.CONVOSKETCHPAD_AUTH_FAILURE_WINDOW) authLines.push(`CONVOSKETCHPAD_AUTH_FAILURE_WINDOW=${config.CONVOSKETCHPAD_AUTH_FAILURE_WINDOW}`);
    if (config.CONVOSKETCHPAD_AUTH_LOCKOUT) authLines.push(`CONVOSKETCHPAD_AUTH_LOCKOUT=${config.CONVOSKETCHPAD_AUTH_LOCKOUT}`);
    lines.push('# Authentication');
    lines.push(...authLines);
    lines.push('');
  }

  // Advanced
  const advLines: string[] = [];
  if (config.ALLOWED_ORIGINS) advLines.push(`ALLOWED_ORIGINS=${config.ALLOWED_ORIGINS}`);
  if (config.TRUSTED_PROXIES) advLines.push(`TRUSTED_PROXIES=${config.TRUSTED_PROXIES}`);
  if (config.CONVOSKETCHPAD_DATA_DIR) advLines.push(`CONVOSKETCHPAD_DATA_DIR=${config.CONVOSKETCHPAD_DATA_DIR}`);
  if (config.CONVOSKETCHPAD_ALLOW_INSECURE) advLines.push(`CONVOSKETCHPAD_ALLOW_INSECURE=${config.CONVOSKETCHPAD_ALLOW_INSECURE}`);
  if (advLines.length > 0) {
    lines.push('# Advanced');
    lines.push(...advLines);
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Write .env file atomically (write .env.tmp then rename).
 */
export function writeEnvFile(envPath: string, config: EnvConfig): void {
  const content = generateEnvContent(config);
  const tmpPath = envPath + '.tmp';
  writeFileSync(tmpPath, content, 'utf-8');
  renameSync(tmpPath, envPath);
  try { chmodSync(envPath, 0o600); } catch { /* non-fatal on Windows */ }
}

/**
 * Parse an existing .env file into key-value pairs.
 */
export function loadExistingEnv(envPath: string): EnvConfig {
  const content = readFileSync(envPath, 'utf-8');
  const config: Record<string, string> = {};
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx > 0) {
      const key = trimmed.slice(0, eqIdx).trim();
      let value = trimmed.slice(eqIdx + 1).trim();
      // Strip matching surrounding quotes ("value" or 'value')
      if (value.length >= 2 && ((value[0] === '"' && value[value.length - 1] === '"') || (value[0] === "'" && value[value.length - 1] === "'"))) {
        value = value.slice(1, -1);
      }
      if (value || key === 'AGENT_RUNTIMES') config[key] = value;
    }
  }
  const legacyMappings = [
    ['AGENT_BACKENDS', 'AGENT_RUNTIMES'],
    ['GATEWAY_URL', 'OPENCLAW_GATEWAY_URL'],
    ['GATEWAY_TOKEN', 'OPENCLAW_GATEWAY_TOKEN'],
    ['CONVOSKETCHPAD_GATEWAY_TIMEZONE', 'OPENCLAW_GATEWAY_TIMEZONE'],
  ] as const;
  for (const [legacyKey, currentKey] of legacyMappings) {
    const legacy = config[legacyKey];
    const current = config[currentKey];
    if (legacy !== undefined && current !== undefined && legacy !== current) {
      throw new Error(`Conflicting ${legacyKey} and ${currentKey} values`);
    }
    if (legacy !== undefined && current === undefined) config[currentKey] = legacy;
    delete config[legacyKey];
  }
  if (config.AGENT_RUNTIMES === undefined) config.AGENT_RUNTIMES = 'openclaw';
  return config as EnvConfig;
}

/**
 * Backup existing .env file before overwriting.
 * Uses timestamped backup if .env.backup already exists.
 */
export function backupExistingEnv(envPath: string): string {
  const backupPath = `${envPath}.backup`;
  if (existsSync(backupPath)) {
    const dated = `${backupPath}.${new Date().toISOString().slice(0, 10)}`;
    copyFileSync(envPath, dated);
    try { chmodSync(dated, 0o600); } catch { /* non-fatal */ }
    return dated;
  }
  copyFileSync(envPath, backupPath);
  try { chmodSync(backupPath, 0o600); } catch { /* non-fatal */ }
  return backupPath;
}

/** Restore the exact pre-setup .env state after a later setup phase fails. */
export function restoreEnvAfterFailedSetup(envPath: string, backupPath?: string): void {
  if (backupPath) {
    copyFileSync(backupPath, envPath);
    try { chmodSync(envPath, 0o600); } catch { /* non-fatal on Windows */ }
    return;
  }
  try {
    unlinkSync(envPath);
  } catch (error) {
    if (!(error && typeof error === 'object' && 'code' in error && error.code === 'ENOENT')) {
      throw error;
    }
  }
}

/**
 * Clean up .env.tmp if it exists (interrupted setup).
 */
export function cleanupTmp(envPath: string): void {
  const tmpPath = envPath + '.tmp';
  try {
    if (existsSync(tmpPath)) {
      unlinkSync(tmpPath);
    }
  } catch {
    // ignore cleanup failures
  }
}
