/**
 * .env file generator — reads, writes, and backs up .env files.
 */

import { readFileSync, writeFileSync, renameSync, copyFileSync, existsSync, unlinkSync, chmodSync } from 'node:fs';

/** All supported env config keys. */
export interface EnvConfig {
  AGENT_BACKENDS?: string;
  OPENCLAW_GATEWAY_URL?: string;
  OPENCLAW_GATEWAY_TOKEN?: string;
  OPENCLAW_GATEWAY_TIMEZONE?: string;
  OPENCLAW_CONFIG_PATH?: string;
  OPENCLAW_BIN?: string;
  PORT?: string;
  HOST?: string;
  ALLOWED_ORIGINS?: string;
  TRUSTED_PROXIES?: string;
  CONVOSKETCHPAD_DATA_DIR?: string;
  CONVOSKETCHPAD_ALLOW_INSECURE?: string;
  // Authentication
  CONVOSKETCHPAD_AUTH?: string;
  CONVOSKETCHPAD_SESSION_SECRET?: string;
  CONVOSKETCHPAD_SESSION_TTL?: string;
  CONVOSKETCHPAD_AUTH_MAX_FAILURES?: string;
  CONVOSKETCHPAD_AUTH_FAILURE_WINDOW?: string;
  CONVOSKETCHPAD_AUTH_LOCKOUT?: string;
}

/** Default values (matching server/lib/config.ts). */
export const DEFAULTS: Record<string, string> = {
  OPENCLAW_GATEWAY_URL: 'http://127.0.0.1:18789',
  PORT: '3080',
  HOST: '127.0.0.1',
};

/**
 * Generate a clean .env file.
 * Only writes values that differ from defaults (keeps .env minimal).
 * Always writes OPENCLAW_GATEWAY_TOKEN since it has no default.
 */
export function generateEnvContent(config: EnvConfig): string {
  const lines: string[] = [
    '# ConvoSketchpad Configuration',
    '# Generated by `npm run setup`',
    `# ${new Date().toISOString()}`,
    '',
  ];

  // Gateway (always written — most important)
  lines.push(`AGENT_BACKENDS=${config.AGENT_BACKENDS || 'openclaw'}`);
  lines.push('');
  lines.push('# OpenClaw Gateway');
  if (config.OPENCLAW_GATEWAY_URL && config.OPENCLAW_GATEWAY_URL !== DEFAULTS.OPENCLAW_GATEWAY_URL) {
    lines.push(`OPENCLAW_GATEWAY_URL=${config.OPENCLAW_GATEWAY_URL}`);
  }
  lines.push(`OPENCLAW_GATEWAY_TOKEN=${config.OPENCLAW_GATEWAY_TOKEN || ''}`);
  if (config.OPENCLAW_GATEWAY_TIMEZONE) {
    lines.push(`OPENCLAW_GATEWAY_TIMEZONE=${config.OPENCLAW_GATEWAY_TIMEZONE}`);
  }
  if (config.OPENCLAW_CONFIG_PATH) lines.push(`OPENCLAW_CONFIG_PATH=${config.OPENCLAW_CONFIG_PATH}`);
  if (config.OPENCLAW_BIN) lines.push(`OPENCLAW_BIN=${config.OPENCLAW_BIN}`);
  lines.push('');

  // Server — always write PORT for clarity (even if default)
  const serverLines: string[] = [];
  serverLines.push(`PORT=${config.PORT || DEFAULTS.PORT}`);
  if (config.HOST && config.HOST !== DEFAULTS.HOST) {
    serverLines.push(`HOST=${config.HOST}`);
  }
  lines.push('# Server');
  lines.push(...serverLines);
  lines.push('');

  // Authentication
  if (
    config.CONVOSKETCHPAD_AUTH === 'true'
    || config.CONVOSKETCHPAD_SESSION_SECRET
    || config.CONVOSKETCHPAD_SESSION_TTL
    || config.CONVOSKETCHPAD_AUTH_MAX_FAILURES
    || config.CONVOSKETCHPAD_AUTH_FAILURE_WINDOW
    || config.CONVOSKETCHPAD_AUTH_LOCKOUT
  ) {
    const authLines: string[] = [];
    authLines.push(`CONVOSKETCHPAD_AUTH=${config.CONVOSKETCHPAD_AUTH || 'false'}`);
    if (config.CONVOSKETCHPAD_SESSION_SECRET) authLines.push(`CONVOSKETCHPAD_SESSION_SECRET=${config.CONVOSKETCHPAD_SESSION_SECRET}`);
    if (config.CONVOSKETCHPAD_SESSION_TTL) authLines.push(`CONVOSKETCHPAD_SESSION_TTL=${config.CONVOSKETCHPAD_SESSION_TTL}`);
    if (config.CONVOSKETCHPAD_AUTH_MAX_FAILURES) authLines.push(`CONVOSKETCHPAD_AUTH_MAX_FAILURES=${config.CONVOSKETCHPAD_AUTH_MAX_FAILURES}`);
    if (config.CONVOSKETCHPAD_AUTH_FAILURE_WINDOW) authLines.push(`CONVOSKETCHPAD_AUTH_FAILURE_WINDOW=${config.CONVOSKETCHPAD_AUTH_FAILURE_WINDOW}`);
    if (config.CONVOSKETCHPAD_AUTH_LOCKOUT) authLines.push(`CONVOSKETCHPAD_AUTH_LOCKOUT=${config.CONVOSKETCHPAD_AUTH_LOCKOUT}`);
    lines.push('# Authentication');
    lines.push(...authLines);
    lines.push('');
  }

  // Advanced
  const advLines: string[] = [];
  if (config.ALLOWED_ORIGINS) advLines.push(`ALLOWED_ORIGINS=${config.ALLOWED_ORIGINS}`);
  if (config.TRUSTED_PROXIES) advLines.push(`TRUSTED_PROXIES=${config.TRUSTED_PROXIES}`);
  if (config.CONVOSKETCHPAD_DATA_DIR) advLines.push(`CONVOSKETCHPAD_DATA_DIR=${config.CONVOSKETCHPAD_DATA_DIR}`);
  if (config.CONVOSKETCHPAD_ALLOW_INSECURE) advLines.push(`CONVOSKETCHPAD_ALLOW_INSECURE=${config.CONVOSKETCHPAD_ALLOW_INSECURE}`);
  if (advLines.length > 0) {
    lines.push('# Advanced');
    lines.push(...advLines);
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Write .env file atomically (write .env.tmp then rename).
 */
export function writeEnvFile(envPath: string, config: EnvConfig): void {
  const content = generateEnvContent(config);
  const tmpPath = envPath + '.tmp';
  writeFileSync(tmpPath, content, 'utf-8');
  renameSync(tmpPath, envPath);
  try { chmodSync(envPath, 0o600); } catch { /* non-fatal on Windows */ }
}

/**
 * Parse an existing .env file into key-value pairs.
 */
export function loadExistingEnv(envPath: string): EnvConfig {
  const content = readFileSync(envPath, 'utf-8');
  const config: Record<string, string> = {};
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx > 0) {
      const key = trimmed.slice(0, eqIdx).trim();
      let value = trimmed.slice(eqIdx + 1).trim();
      // Strip matching surrounding quotes ("value" or 'value')
      if (value.length >= 2 && ((value[0] === '"' && value[value.length - 1] === '"') || (value[0] === "'" && value[value.length - 1] === "'"))) {
        value = value.slice(1, -1);
      }
      if (value) config[key] = value;
    }
  }
  const legacyMappings = [
    ['GATEWAY_URL', 'OPENCLAW_GATEWAY_URL'],
    ['GATEWAY_TOKEN', 'OPENCLAW_GATEWAY_TOKEN'],
    ['CONVOSKETCHPAD_GATEWAY_TIMEZONE', 'OPENCLAW_GATEWAY_TIMEZONE'],
  ] as const;
  for (const [legacyKey, currentKey] of legacyMappings) {
    const legacy = config[legacyKey];
    const current = config[currentKey];
    if (legacy && current && legacy !== current) {
      throw new Error(`Conflicting ${legacyKey} and ${currentKey} values`);
    }
    if (legacy && !current) config[currentKey] = legacy;
    delete config[legacyKey];
  }
  config.AGENT_BACKENDS ||= 'openclaw';
  return config as EnvConfig;
}

/**
 * Backup existing .env file before overwriting.
 * Uses timestamped backup if .env.backup already exists.
 */
export function backupExistingEnv(envPath: string): string {
  const backupPath = `${envPath}.backup`;
  if (existsSync(backupPath)) {
    const dated = `${backupPath}.${new Date().toISOString().slice(0, 10)}`;
    copyFileSync(envPath, dated);
    try { chmodSync(dated, 0o600); } catch { /* non-fatal */ }
    return dated;
  }
  copyFileSync(envPath, backupPath);
  try { chmodSync(backupPath, 0o600); } catch { /* non-fatal */ }
  return backupPath;
}

/**
 * Clean up .env.tmp if it exists (interrupted setup).
 */
export function cleanupTmp(envPath: string): void {
  const tmpPath = envPath + '.tmp';
  try {
    if (existsSync(tmpPath)) {
      unlinkSync(tmpPath);
    }
  } catch {
    // ignore cleanup failures
  }
}
